In [4]:
import torch.nn.functional as F
import torch

In [23]:
x = torch.tensor([[1, 2, 3, 4, 5], [1, 7, 8, 9, 15]], dtype=torch.float32)
x

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 1.,  7.,  8.,  9., 15.]])

In [24]:
hypothesis = F.softmax(x, dim=1)
hypothesis

tensor([[1.1656e-02, 3.1685e-02, 8.6129e-02, 2.3412e-01, 6.3641e-01],
        [8.2844e-07, 3.3422e-04, 9.0850e-04, 2.4695e-03, 9.9629e-01]])

In [20]:
hypothesis.sum(dim=1, keepdim=True)

tensor([[1.0000],
        [1.0000]])

In [26]:
y = torch.tensor([2, 3])
y

tensor([2, 3])

In [27]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1) # dim=1, y.unsqueeze(1), 1대입

tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [30]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
cost

tensor(4.2278)

In [31]:
cost = (y_one_hot * -F.log_softmax(x, dim=1)).sum(dim=1).mean()
cost

tensor(4.2278)

In [33]:
F.nll_loss(F.log_softmax(x, dim=1), y)

tensor(4.2278)

In [34]:
F.cross_entropy(x, y)

tensor(4.2278)